FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build TypeScript files
RUN npm run build

# Start cron worker
CMD ["node", "dist/start-cron.js"] 