export enum LogType {
  WATERING = 'WATERING',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  LST = 'LST',
  HST = 'HST',
  HARVEST = 'HARVEST',
  DRYING = 'DRYING',
  PEST_STRESS_DISEASE = 'PEST_STRESS_DISEASE',
  TRANSPLANT = 'TRANSPLANT',
  TRANSFER = 'TRANSFER',
  GERMINATION = 'GERMINATION',
  CLONING = 'CLONING',
  INSPECTION = 'INSPECTION',
  TREATMENT = 'TREATMENT',
  EQUIPMENT = 'EQUIPMENT'
}

export enum Stage {
  SEEDLING = 'SEEDLING',
  VEGETATIVE = 'VEGETATIVE',
  FLOWERING = 'FLOWERING',
  MOTHER = 'MOTHER',
  CLONE = 'CLONE',
  DRYING = 'DRYING',
  CURING = 'CURING'
}

export enum LightIntensityUnit {
  UMOL_PER_M2_S = 'UMOL_PER_M2_S',
  LUX = 'LUX',
  FOOTCANDLE = 'FOOTCANDLE'
}

export enum DistanceUnit {
  CENTIMETERS = 'CENTIMETERS',
  INCHES = 'INCHES',
  FEET = 'FEET',
  METERS = 'METERS',
  YARDS = 'YARDS'
}

export enum WeightUnit {
  GRAMS = 'GRAMS',
  OUNCES = 'OUNCES',
  POUNDS = 'POUNDS',
  KILOGRAMS = 'KILOGRAMS'
}

export enum VolumeUnit {
  MILLILITERS = 'MILLILITERS',
  LITERS = 'LITERS',
  GALLONS = 'GALLONS',
  FLUID_OUNCES = 'FLUID_OUNCES'
}

export enum TemperatureUnit {
  CELSIUS = 'CELSIUS',
  FAHRENHEIT = 'FAHRENHEIT'
}

export enum WaterSource {
  TAP = 'TAP',
  RO = 'RO',
  WELL = 'WELL',
  FILTERED = 'FILTERED',
  COLLECTED = 'COLLECTED',
  OTHER = 'OTHER'
}

export enum NutrientLine {
  JACKS_321 = 'JACKS_321',
  CUSTOM = 'CUSTOM'
}

export enum Jacks321Product {
  PART_A_5_12_26 = 'PART_A_5_12_26',
  PART_B_15_0_0_CALCIUM_NITRATE = 'PART_B_15_0_0_CALCIUM_NITRATE',
  PART_C_EPSOM_SALT = 'PART_C_EPSOM_SALT',
  BLOSSOMBOOST_10_30_20 = 'BLOSSOMBOOST_10_30_20',
  FINISH_7_15_30 = 'FINISH_7_15_30'
}

export enum PestType {
  SPIDER_MITES = 'SPIDER_MITES',
  BROAD_MITES = 'BROAD_MITES',
  RUSSET_MITES = 'RUSSET_MITES',
  THRIPS = 'THRIPS',
  APHIDS = 'APHIDS',
  FUNGUS_GNATS = 'FUNGUS_GNATS',
  WHITEFLIES = 'WHITEFLIES',
  ROOT_APHIDS = 'ROOT_APHIDS',
  ASIAN_LADY_BEETLES = 'ASIAN_LADY_BEETLES',
  BOX_ELDERS = 'BOX_ELDERS',
  STINK_BUGS = 'STINK_BUGS',
  MICE_RODENTS = 'MICE_RODENTS',
  DEER = 'DEER',
  BIRDS = 'BIRDS',
  RABBITS = 'RABBITS',
  GROUNDHOGS = 'GROUNDHOGS',
  MOLES = 'MOLES',
  ANTS = 'ANTS',
  SLUGS = 'SLUGS',
  JUNE_BUGS = 'JUNE_BUGS',
  OTHER = 'OTHER'
}

export enum PestCategory {
  INSECT = 'INSECT',
  FUNGI = 'FUNGI',
  BACTERIA = 'BACTERIA',
  VIRUS = 'VIRUS',
  OTHER = 'OTHER'
}

export enum DiseaseType {
  POWDERY_MILDEW = 'POWDERY_MILDEW',
  BOTRYTIS = 'BOTRYTIS',
  ROOT_ROT = 'ROOT_ROT',
  LEAF_SEPTORIA = 'LEAF_SEPTORIA',
  FUSARIUM_WILT = 'FUSARIUM_WILT',
  OTHER = 'OTHER'
}

export enum TreatmentMethod {
  FOLIAR_SPRAY = 'FOLIAR_SPRAY',
  SOIL_DRENCH = 'SOIL_DRENCH',
  BENEFICIAL_INSECTS = 'BENEFICIAL_INSECTS',
  ENVIRONMENTAL_ADJUSTMENT = 'ENVIRONMENTAL_ADJUSTMENT',
  MANUAL_REMOVAL = 'MANUAL_REMOVAL',
  OTHER = 'OTHER'
}

export enum TrainingMethod {
  TOP = 'TOP',
  FIM = 'FIM',
  LST = 'LST',
  SCROG = 'SCROG',
  SUPER_CROP = 'SUPER_CROP',
  LOLLIPOP = 'LOLLIPOP',
  TRELLIS = 'TRELLIS',
  OTHER = 'OTHER'
}

export enum DetectionMethod {
  VISUAL = 'VISUAL',
  SOIL_MOISTURE_METER = 'SOIL_MOISTURE_METER',
  PH_EC_METER = 'PH_EC_METER',
  IR_THERMOMETER = 'IR_THERMOMETER',
  LEAF_SURFACE_SCAN = 'LEAF_SURFACE_SCAN',
  OTHER = 'OTHER'
}

export enum StressDuration {
  LESS_THAN_ONE_HOUR = 'LESS_THAN_ONE_HOUR',
  ONE_TO_SIX_HOURS = 'ONE_TO_SIX_HOURS',
  SIX_TO_TWENTY_FOUR_HOURS = 'SIX_TO_TWENTY_FOUR_HOURS',
  ONE_TO_THREE_DAYS = 'ONE_TO_THREE_DAYS',
  ONGOING = 'ONGOING',
  UNSURE = 'UNSURE'
}

export enum ExpectedRecoveryTime {
  LESS_THAN_ONE_DAY = 'LESS_THAN_ONE_DAY',
  ONE_TO_THREE_DAYS = 'ONE_TO_THREE_DAYS',
  THREE_TO_SEVEN_DAYS = 'THREE_TO_SEVEN_DAYS',
  MORE_THAN_ONE_WEEK = 'MORE_THAN_ONE_WEEK',
  UNKNOWN = 'UNKNOWN'
}

export enum SuspectedStressCause {
  HEAT = 'HEAT',
  LIGHT_BURN = 'LIGHT_BURN',
  OVERWATERING = 'OVERWATERING',
  UNDERWATERING = 'UNDERWATERING',
  PH_IMBALANCE = 'PH_IMBALANCE',
  TOXICITY_ABUNDANCE = 'TOXICITY_ABUNDANCE',
  DEFICIENCY = 'DEFICIENCY',
  PHYSICAL_DAMAGE = 'PHYSICAL_DAMAGE',
  PEST = 'PEST',
  FUNGUS = 'FUNGUS',
  BACTERIA = 'BACTERIA',
  DISEASE = 'DISEASE',
  COLD_STRESS = 'COLD_STRESS',
  ROOT_BOUND = 'ROOT_BOUND',
  TRANSPLANT_SHOCK = 'TRANSPLANT_SHOCK',
  CHEMICAL_DAMAGE = 'CHEMICAL_DAMAGE',
  FOLIAR_SPRAY_DAMAGE = 'FOLIAR_SPRAY_DAMAGE',
  OTHER = 'OTHER'
}

type StressSymptom =
  | 'STUNTED_GROWTH'
  | 'SLOW_RECOVERY'
  | 'PALE_COLOR'
  | 'UNEVEN_GROWTH'
  | 'ABNORMAL_SPACING'
  | 'BRITTLE_STEMS'
  | 'WEAK_BRANCHING'
  | 'UNEXPLAINED_DROP'
  | 'SCENT_CHANGE'
  | 'HEAT_STRESS'
  | 'COLD_STRESS'
  | 'ROOT_BOUND'
  | 'PHYSICAL_DAMAGE'
  | 'TRANSPLANT_SHOCK'
  | 'CHEMICAL_SPRAY_DAMAGE'
  | 'LIGHT_BURN'
  | 'STRETCHING'
  | 'TIP_CURL'
  | 'OVER_TRANSPIRATION'
  | 'NUTRIENT_LOCKOUT'
  | 'OTHER'; 