export enum Stage {
  SEEDLING = 'SEEDLING',
  VEGETATIVE = 'VEGETATIVE',
  FLOWERING = 'FLOWERING',
  MOTHER = 'MOTHER',
  CLONE = 'CLONE',
  DRYING = 'DRYING',
  CURING = 'CURING'
}

export enum LogType {
  WATERING = 'WATERING',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  LST = 'LST',
  FLUSHING = 'FLUSHING',
  HARVEST = 'HARVEST',
  PEST_DISEASE = 'PEST_DISEASE',
  TRANSPLANT = 'TRANSPLANT',
  GERMINATION = 'GERMINATION',
  CLONING = 'CLONING',
  INSPECTION = 'INSPECTION',
  TREATMENT = 'TREATMENT',
  STRESS = 'STRESS',
  GENERAL = 'GENERAL',
  CUSTOM = 'CUSTOM'
}

export enum WaterSource {
  TAP = 'TAP',
  RO = 'RO',
  WELL = 'WELL',
  FILTERED = 'FILTERED',
  COLLECTED = 'COLLECTED',
  OTHER = 'OTHER'
}

export enum NutrientLine {
  JACKS_321 = 'JACKS_321',
  CUSTOM = 'CUSTOM'
}

export enum Jacks321Product {
  PART_A_5_12_26 = 'PART_A_5_12_26',
  PART_B_15_0_0_CALCIUM_NITRATE = 'PART_B_15_0_0_CALCIUM_NITRATE',
  PART_C_EPSOM_SALT = 'PART_C_EPSOM_SALT',
  BOOSTER = 'BOOSTER',
  FINISH = 'FINISH'
}

export enum TemperatureUnit {
  CELSIUS = 'CELSIUS',
  FAHRENHEIT = 'FAHRENHEIT'
}

export enum LengthUnit {
  CENTIMETERS = 'CENTIMETERS',
  INCHES = 'INCHES'
}

export enum VolumeUnit {
  MILLILITERS = 'MILLILITERS',
  FLUID_OUNCES = 'FLUID_OUNCES',
  LITERS = 'LITERS',
  GALLONS = 'GALLONS'
}

export enum WeightUnit {
  GRAMS = 'GRAMS',
  OUNCES = 'OUNCES',
  KILOGRAMS = 'KILOGRAMS',
  POUNDS = 'POUNDS'
}

export enum HealthRating {
  EXCELLENT = 'EXCELLENT',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  POOR = 'POOR',
  CRITICAL = 'CRITICAL'
}

export enum PruningType {
  TOPPING = 'TOPPING',
  LOLLIPOPPING = 'LOLLIPOPPING',
  DEFOLIATION = 'DEFOLIATION',
  TRIMMING = 'TRIMMING'
}

export enum TrainingMethod {
  TOP = 'TOP',
  FIM = 'FIM',
  LST = 'LST',
  SCROG = 'SCROG',
  SUPER_CROP = 'SUPER_CROP',
  LOLLIPOP = 'LOLLIPOP',
  OTHER = 'OTHER'
}

export enum PestType {
  SPIDER_MITES = 'SPIDER_MITES',
  THRIPS = 'THRIPS',
  APHIDS = 'APHIDS',
  FUNGUS_GNATS = 'FUNGUS_GNATS',
  WHITEFLIES = 'WHITEFLIES',
  ROOT_APHIDS = 'ROOT_APHIDS',
  OTHER = 'OTHER'
}

export enum DiseaseType {
  POWDERY_MILDEW = 'POWDERY_MILDEW',
  BOTRYTIS = 'BOTRYTIS',
  ROOT_ROT = 'ROOT_ROT',
  LEAF_SEPTORIA = 'LEAF_SEPTORIA',
  FUSARIUM_WILT = 'FUSARIUM_WILT',
  OTHER = 'OTHER'
}

export enum TreatmentMethod {
  FOLIAR_SPRAY = 'FOLIAR_SPRAY',
  SOIL_DRENCH = 'SOIL_DRENCH',
  BENEFICIAL_INSECTS = 'BENEFICIAL_INSECTS',
  ENVIRONMENTAL_ADJUSTMENT = 'ENVIRONMENTAL_ADJUSTMENT',
  MANUAL_REMOVAL = 'MANUAL_REMOVAL',
  OTHER = 'OTHER'
}

export enum StressType {
  HEAT = 'HEAT',
  COLD = 'COLD',
  DROUGHT = 'DROUGHT',
  OVERWATERING = 'OVERWATERING',
  NUTRIENT_DEFICIENCY = 'NUTRIENT_DEFICIENCY',
  NUTRIENT_TOXICITY = 'NUTRIENT_TOXICITY',
  LIGHT_BURN = 'LIGHT_BURN',
  LIGHT_STRESS = 'LIGHT_STRESS',
  PH_ISSUES = 'PH_ISSUES',
  OTHER = 'OTHER'
}

export enum SuspectedStressCause {
  HEAT = 'HEAT',
  LIGHT_BURN = 'LIGHT_BURN',
  OVERWATERING = 'OVERWATERING',
  UNDERWATERING = 'UNDERWATERING',
  NUTRIENT_DEFICIENCY = 'NUTRIENT_DEFICIENCY',
  NUTRIENT_BURN = 'NUTRIENT_BURN',
  PH_IMBALANCE = 'PH_IMBALANCE',
  PEST_DAMAGE = 'PEST_DAMAGE',
  DISEASE = 'DISEASE',
  ENVIRONMENTAL_STRESS = 'ENVIRONMENTAL_STRESS',
  TRANSPLANT_SHOCK = 'TRANSPLANT_SHOCK',
  ROOT_BOUND = 'ROOT_BOUND',
  TOXICITY_ABUNDANCE = 'TOXICITY_ABUNDANCE',
  OTHER = 'OTHER'
}

export enum LightIntensityUnit {
  LUX = 'LUX',
  FOOT_CANDLES = 'FOOT_CANDLES',
  PAR = 'PAR',
  PPFD = 'PPFD'
}

export enum DistanceUnit {
  INCHES = 'INCHES',
  CENTIMETERS = 'CENTIMETERS',
  FEET = 'FEET',
  METERS = 'METERS'
}

export enum PestCategory {
  INSECTS = 'INSECTS',
  MITES = 'MITES',
  FUNGI = 'FUNGI',
  BACTERIA = 'BACTERIA',
  VIRUSES = 'VIRUSES',
  NEMATODES = 'NEMATODES',
  OTHER = 'OTHER'
}

export enum LSTIntensity {
  LIGHT = 'LIGHT',
  MODERATE = 'MODERATE',
  INTENSE = 'INTENSE'
}

export enum CanopyShape {
  EVEN = 'EVEN',
  SLOPED = 'SLOPED',
  SUPER_UNEVEN = 'SUPER_UNEVEN'
} 