export enum Stage {
  SEEDLING = 'SEEDLING',
  VEGETATIVE = 'VEGETATIVE',
  FLOWERING = 'FLOWERING',
  HARVEST = 'HARVEST',
  DRYING = 'DRYING',
  CURING = 'CURING'
}

export enum LogType {
  WATERING = 'WATERING',
  FEEDING = 'FEEDING',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  PRUNING = 'PRUNING',
  TRAINING = 'TRAINING',
  DEFOLIATION = 'DEFOLIATION',
  FLUSHING = 'FLUSHING',
  HARVEST = 'HARVEST',
  PEST_DISEASE = 'PEST_DISEASE',
  GENERAL = 'GENERAL'
} 